export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const EDIT_CANCEL = 'EDIT_CANCEL';
export const SAVE_CHANGES = 'SAVE_CHANGES';
export const SEARCH_SERVICE = 'SEARCH_SERVICE';